@ShiftsLogger.API_HostAddress = http://localhost:5111

###
POST {{ShiftsLogger.API_HostAddress}}/shift
Accept: application/json
###
PUT {{ShiftsLogger.API_HostAddress}}/shift/3/stop
Accept: application/json
###
GET {{ShiftsLogger.API_HostAddress}}/shift/
Accept: application/json
###
